name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: stage

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
      with:
        path: /data/testing/
